"""Contracts and result models for capability lifecycles."""

from lifecycle.capability.lifecycle import CapabilityLifecycle, LifecycleSnapshotReader
from lifecycle.capability.projection import CapabilityProjector
from lifecycle.capability.result import (
    AcquireResult,
    LifecycleDiagnostics,
    LifecycleOutcome,
    LifecycleResult,
    RecoveryResult,
    ReleaseResult,
)
from lifecycle.capability.session import (
    CapabilitySessionFactory,
    CleanupReport,
    DefaultCapabilitySessionFactory,
    PreparationFailed,
    PreparedSession,
    SessionOwner,
)
from lifecycle.capability.snapshot import CleanupOrigin, LifecyclePhase, LifecycleSnapshot
from lifecycle.capability.supervision import (
    AcquireDisposition,
    AcquireSupervisionPolicy,
    AcquireSupervisionResult,
    AcquireSupervisor,
    CancellationSignal,
    RecoveryDisposition,
    RecoverySupervisionPolicy,
    RecoverySupervisionResult,
    RecoverySupervisor,
    ReleaseDisposition,
    ReleaseSupervisionPolicy,
    ReleaseSupervisionResult,
    ReleaseSupervisor,
    SupervisionStopped,
    SupervisionStopReason,
    classify_acquire_result,
    classify_recovery_result,
    classify_release_result,
)


__all__ = [
    "AcquireDisposition",
    "AcquireResult",
    "AcquireSupervisionPolicy",
    "AcquireSupervisionResult",
    "AcquireSupervisor",
    "CancellationSignal",
    "CapabilityLifecycle",
    "CapabilityProjector",
    "CapabilitySessionFactory",
    "CleanupOrigin",
    "CleanupReport",
    "DefaultCapabilitySessionFactory",
    "LifecycleDiagnostics",
    "LifecycleOutcome",
    "LifecyclePhase",
    "LifecycleResult",
    "LifecycleSnapshot",
    "LifecycleSnapshotReader",
    "PreparationFailed",
    "PreparedSession",
    "RecoveryDisposition",
    "RecoveryResult",
    "RecoverySupervisionPolicy",
    "RecoverySupervisionResult",
    "RecoverySupervisor",
    "ReleaseDisposition",
    "ReleaseResult",
    "ReleaseSupervisionPolicy",
    "ReleaseSupervisionResult",
    "ReleaseSupervisor",
    "SessionOwner",
    "SupervisionStopped",
    "SupervisionStopReason",
    "classify_acquire_result",
    "classify_recovery_result",
    "classify_release_result",
]
